// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRhoSipoc-AQqLKhRUc0J-fOa3mRzq_GU',
    appId: '1:538781243596:android:5e0471620d09511fb8ca69',
    messagingSenderId: '538781243596',
    projectId: 'hang-7',
    storageBucket: 'hang-7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNjfGqek-vV7rFWzu83ZjOhdPIsvTuiPg',
    appId: '1:538781243596:ios:8a72494e4b209ad4b8ca69',
    messagingSenderId: '538781243596',
    projectId: 'hang-7',
    storageBucket: 'hang-7.appspot.com',
    iosClientId: '538781243596-iin6b13bkch4i2g0e7rvmof1tuja2d1d.apps.googleusercontent.com',
    iosBundleId: 'com.blB.hang7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNjfGqek-vV7rFWzu83ZjOhdPIsvTuiPg',
    appId: '1:538781243596:ios:8a72494e4b209ad4b8ca69',
    messagingSenderId: '538781243596',
    projectId: 'hang-7',
    storageBucket: 'hang-7.appspot.com',
    iosClientId: '538781243596-iin6b13bkch4i2g0e7rvmof1tuja2d1d.apps.googleusercontent.com',
    iosBundleId: 'com.blB.hang7',
  );
}
